import React, { useState } from 'react';
import { SaleItem, InventoryItem, DayReport, Expense } from '../types';
import { formatCurrency, generateId } from '../utils/pricing';
import { saveDayReportToCloud } from '../services/storageService';
import { Download, TrendingUp, Save, LogOut, Wallet, Plus, Trash2, QrCode, AlertTriangle, RefreshCw, Loader2, Leaf, Calendar, X } from 'lucide-react';
import { jsPDF } from "jspdf";

interface DailyReportProps {
  sales: SaleItem[];
  expenses: Expense[];
  inventory: InventoryItem[];
  onDeleteSale: (sale: SaleItem) => void;
  onAddExpense: (description: string, amount: number) => Promise<void>;
  onDeleteExpense: (id: string) => Promise<void>;
  onReset: () => Promise<void>;
  deletingIds: Set<string>;
  shopName: string;
  staffName: string;
}

export const DailyReport: React.FC<DailyReportProps> = ({ 
  sales, expenses, inventory, onDeleteSale, onAddExpense, onDeleteExpense, onReset, deletingIds, shopName, staffName
}) => {
  const [savingReport, setSavingReport] = useState(false);
  const [expDesc, setExpDesc] = useState('');
  const [expAmount, setExpAmount] = useState('');
  
  // Delete Modal State
  const [saleToDelete, setSaleToDelete] = useState<SaleItem | null>(null);

  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const [confirmReset, setConfirmReset] = useState(false);

  const totalRevenue = sales.reduce((sum, sale) => sum + sale.price, 0);
  const totalExpenses = expenses.reduce((sum, exp) => sum + exp.amount, 0);
  const netIncome = totalRevenue - totalExpenses;
  const totalItems = sales.length;
  
  const handleSaveAndArchive = async () => {
    setSavingReport(true);
    let shopId = shopName.toLowerCase().includes('near') ? 'nearcannabis' : 'greenspot';
    const report: DayReport = {
        id: `report_${new Date().toISOString().split('T')[0]}_${generateId()}`,
        date: new Date().toISOString().split('T')[0],
        totalSales: sales.length,
        totalRevenue,
        itemsSold: sales.reduce((sum, s) => sum + s.quantity, 0),
        sales: sales,
        expenses: expenses,
        timestamp: Date.now(),
        closedBy: staffName
    };
    await saveDayReportToCloud(shopId, report);
    setSavingReport(false);
    alert("Saved to Archive!");
  };

  const handleNewExpense = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!expDesc || !expAmount) return;
    await onAddExpense(expDesc, Number(expAmount));
    setExpDesc('');
    setExpAmount('');
  };

  const handleDownloadPDF = () => {
    setDownloadingPdf(true);
    
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const dateStr = new Date().toLocaleDateString();
      const timeStr = new Date().toLocaleTimeString();

      // -- HEADER --
      doc.setFontSize(22);
      doc.setTextColor(22, 163, 74); // Green 600
      doc.setFont("helvetica", "bold");
      doc.text(shopName, 15, 20);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.setFont("helvetica", "normal");
      doc.text(`Daily Sales Report • ${dateStr} ${timeStr}`, pageWidth - 15, 20, { align: 'right' });
      doc.text(`Generated by ${staffName}`, pageWidth - 15, 25, { align: 'right' });

      doc.setDrawColor(220);
      doc.setLineWidth(0.5);
      doc.line(15, 30, pageWidth - 15, 30);

      // -- SUMMARY CARDS --
      // 1. Total Revenue (Green)
      doc.setFillColor(240, 253, 244); // Green 50
      doc.roundedRect(15, 35, 60, 25, 3, 3, 'F');
      doc.setFontSize(8);
      doc.setTextColor(21, 128, 61); // Green 700
      doc.text("TOTAL REVENUE", 20, 42);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(`${totalRevenue.toLocaleString()} THB`, 20, 52);

      // 2. Net Income (Blue)
      doc.setFillColor(239, 246, 255); // Blue 50
      doc.roundedRect(80, 35, 60, 25, 3, 3, 'F');
      doc.setFontSize(8);
      doc.setTextColor(29, 78, 216); // Blue 700
      doc.setFont("helvetica", "normal");
      doc.text("NET INCOME", 85, 42);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(`${netIncome.toLocaleString()} THB`, 85, 52);

      // 3. Transactions (Gray)
      doc.setFillColor(248, 250, 252); // Slate 50
      doc.roundedRect(145, 35, 50, 25, 3, 3, 'F');
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.setFont("helvetica", "normal");
      doc.text("TRANSACTIONS", 150, 42);
      doc.setFontSize(16);
      doc.setTextColor(30);
      doc.setFont("helvetica", "bold");
      doc.text(totalItems.toString(), 150, 52);

      let yPos = 70;

      // -- TABLE HEADER --
      const headers = ["TIME", "PRODUCT", "TYPE", "QTY", "PRICE"];
      const colWidths = [25, 80, 30, 25, 25]; // Total approx 185
      const startX = 15;
      
      doc.setFillColor(22, 163, 74); // Green 600
      doc.rect(startX, yPos, pageWidth - 30, 8, 'F');
      
      doc.setFontSize(8);
      doc.setTextColor(255);
      doc.setFont("helvetica", "bold");
      
      let currentX = startX + 2;
      headers.forEach((header, i) => {
          doc.text(header, currentX, yPos + 5.5);
          currentX += colWidths[i];
      });

      yPos += 8;

      // -- TABLE ROWS --
      doc.setTextColor(0);
      doc.setFont("helvetica", "normal");

      sales.forEach((sale, index) => {
          if (yPos > 270) {
              doc.addPage();
              yPos = 20;
              // Re-draw header
               doc.setFillColor(22, 163, 74); 
              doc.rect(startX, yPos, pageWidth - 30, 8, 'F');
              doc.setFontSize(8);
              doc.setTextColor(255);
              doc.setFont("helvetica", "bold");
              let cX = startX + 2;
              headers.forEach((header, i) => {
                  doc.text(header, cX, yPos + 5.5);
                  cX += colWidths[i];
              });
              yPos += 8;
              doc.setTextColor(0);
              doc.setFont("helvetica", "normal");
          }

          if (index % 2 === 1) {
              doc.setFillColor(248, 250, 252);
              doc.rect(startX, yPos, pageWidth - 30, 7, 'F');
          }

          currentX = startX + 2;
          
          // Time
          const time = new Date(sale.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
          doc.text(time, currentX, yPos + 5);
          currentX += colWidths[0];

          // Product
          const name = sale.productName.length > 35 ? sale.productName.substring(0, 35) + '...' : sale.productName;
          doc.text(name, currentX, yPos + 5);
          currentX += colWidths[1];

          // Type
          doc.text(sale.productType, currentX, yPos + 5);
          currentX += colWidths[2];

          // Qty
          const unit = sale.productType === 'Flower' ? 'g' : 'u';
          doc.text(`${sale.quantity}${unit}`, currentX, yPos + 5);
          currentX += colWidths[3];

          // Price
          doc.text(sale.price.toLocaleString(), currentX, yPos + 5);

          yPos += 7;
      });

      // -- EXPENSES (if any) --
      if (expenses.length > 0) {
         yPos += 10;
         if (yPos > 260) { doc.addPage(); yPos = 20; }
         
         doc.setFontSize(12);
         doc.setTextColor(185, 28, 28); // Red
         doc.setFont("helvetica", "bold");
         doc.text("EXPENSES", 15, yPos);
         yPos += 6;

         doc.setFontSize(8);
         doc.setTextColor(0);
         doc.setFont("helvetica", "normal");

         expenses.forEach(exp => {
             if (yPos > 280) { doc.addPage(); yPos = 20; }
             doc.text(`• ${exp.description}`, 20, yPos);
             doc.text(`-${exp.amount.toLocaleString()}`, 160, yPos);
             yPos += 5;
         });
      }

      // Footer
      const pageCount = doc.internal.pages.length - 1;
      doc.setFontSize(8);
      doc.setTextColor(150);
      for(let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 290, { align: 'right' });
          doc.text(`The Green Spot POS System`, 20, 290);
      }

      doc.save(`DailySales_${new Date().toISOString().split('T')[0]}.pdf`);

    } catch (error) {
      console.error("PDF Generation failed", error);
      alert("Failed to generate PDF");
    } finally {
      setDownloadingPdf(false);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-fade-in max-w-6xl mx-auto pb-20 relative">
      
      {/* Custom Confirmation Modal */}
      {saleToDelete && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" onClick={() => setSaleToDelete(null)}>
            <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-sm w-full p-6 border border-gray-100 dark:border-gray-700 relative animate-fade-in" onClick={e => e.stopPropagation()}>
                <button onClick={() => setSaleToDelete(null)} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200"><X className="w-5 h-5" /></button>
                <div className="flex justify-center mb-4"><div className="p-3 bg-red-100 dark:bg-red-900/20 rounded-full"><AlertTriangle className="w-8 h-8 text-red-600 dark:text-red-400" /></div></div>
                <h3 className="text-xl font-bold text-center mb-2 text-gray-900 dark:text-white">Void Transaction?</h3>
                <p className="text-center text-gray-500 dark:text-gray-400 text-sm mb-6">Are you sure you want to delete <b>{saleToDelete.productName}</b>? Stock will be restored.</p>
                <div className="grid grid-cols-2 gap-3">
                    <button onClick={() => setSaleToDelete(null)} className="py-3 rounded-xl font-bold bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">Cancel</button>
                    <button onClick={() => { onDeleteSale(saleToDelete); setSaleToDelete(null); }} className="py-3 rounded-xl font-bold bg-red-600 text-white shadow-lg shadow-red-500/30">Confirm Void</button>
                </div>
            </div>
        </div>
      )}

      {/* Left Column: Visual Receipt */}
      <div className="glass-panel p-6 rounded-2xl relative">
          <div id="receipt-container" className="bg-white text-slate-900 p-6 rounded-lg shadow-xl font-mono text-sm relative overflow-hidden">
             {/* Receipt decoration */}
             <div className="absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-green-500 via-green-400 to-green-500"></div>
             
             <div className="text-center mb-6">
                 <h2 className="text-2xl font-black uppercase tracking-widest">{shopName}</h2>
                 <p className="text-xs text-slate-400 uppercase tracking-widest mt-1">{new Date().toLocaleDateString()}</p>
                 <p className="text-[10px] text-slate-400 uppercase tracking-widest mt-1">Daily Sales Report</p>
             </div>

             <div className="border-b-2 border-dashed border-slate-200 pb-2 mb-2 flex justify-between text-xs font-bold text-slate-400 uppercase">
                 <span>Item / Date</span>
                 <span>Amt</span>
             </div>

             <div className="space-y-2 max-h-[400px] overflow-y-auto custom-scrollbar-light pr-2 receipt-scroll">
                 {sales.map((sale, i) => (
                     <div key={sale.id} className="flex justify-between items-start group hover:bg-slate-50 p-1 rounded transition-colors">
                         <div className="flex-1">
                             <div className="font-bold flex items-center text-slate-800">
                                 <span className="text-slate-400 mr-2 text-[10px] w-4">{i + 1}.</span>
                                 {sale.productName}
                                 {sale.paymentMethod === 'Scan' && <QrCode className="w-3 h-3 ml-1 text-blue-500" />}
                             </div>
                             <div className="text-xs text-slate-500 ml-6 flex flex-wrap items-center gap-2">
                                <span>{sale.quantity}{sale.productType === 'Flower'?'g':'u'} {sale.discount ? `(-${sale.discount})` : ''}</span>
                                <span className="text-slate-300">|</span>
                                <span className="flex items-center text-slate-400 text-[10px]">
                                    <Calendar className="w-3 h-3 mr-1" />
                                    {sale.date || new Date(sale.timestamp).toLocaleDateString()}
                                </span>
                             </div>
                         </div>
                         <div className="flex items-center gap-2">
                            <span className="font-bold text-slate-900">{formatCurrency(sale.price)}</span>
                            <button 
                                onClick={() => setSaleToDelete(sale)} 
                                disabled={deletingIds.has(sale.id)}
                                className="text-slate-400 hover:text-red-500 hover:bg-red-50 p-1.5 rounded transition-all ml-2" 
                                data-html2canvas-ignore
                                title="Delete Sale"
                            >
                                {deletingIds.has(sale.id) ? <Loader2 className="w-3 h-3 animate-spin"/> : <Trash2 className="w-3 h-3"/>}
                            </button>
                         </div>
                     </div>
                 ))}
             </div>

             <div className="mt-6 pt-4 border-t-2 border-dashed border-slate-200">
                 <div className="flex justify-between items-center text-lg font-black text-slate-800">
                     <span>TOTAL</span>
                     <span>{formatCurrency(totalRevenue)}</span>
                 </div>
                 {totalExpenses > 0 && (
                     <div className="flex justify-between items-center text-xs text-red-500 mt-1">
                        <span>Expenses</span>
                        <span>-{formatCurrency(totalExpenses)}</span>
                     </div>
                 )}
                 <div className="flex justify-between items-center text-sm font-bold text-green-600 mt-2 border-t border-slate-100 pt-2">
                    <span>NET INCOME</span>
                    <span>{formatCurrency(netIncome)}</span>
                 </div>
             </div>

             <div className="mt-8 text-center text-[10px] text-slate-400 uppercase tracking-widest">
                 Generated by {staffName}
             </div>
          </div>
          
           {/* Download Button Overlaid */}
           <div className="absolute top-8 right-8">
               <button 
                  onClick={handleDownloadPDF}
                  disabled={downloadingPdf}
                  className={`group flex items-center justify-center w-10 h-10 bg-white border border-gray-200 shadow-sm hover:shadow-md hover:border-green-200 rounded-full text-gray-500 hover:text-green-600 transition-all duration-200 ${downloadingPdf ? 'opacity-50 cursor-wait' : ''}`}
                  title="Download Professional PDF Report"
               >
                  {downloadingPdf ? (
                    <Loader2 className="w-5 h-5 animate-spin text-green-600" />
                  ) : (
                    <Download className="w-5 h-5 group-hover:scale-110 transition-transform" />
                  )}
               </button>
           </div>
      </div>

      {/* Right Column: Controls */}
      <div className="space-y-6">
          
          {/* Quick Stats */}
          <div className="grid grid-cols-2 gap-4">
              <div className="glass-card p-4 rounded-xl">
                  <p className="text-xs text-slate-400 uppercase font-bold">Net Sales</p>
                  <p className="text-2xl font-black text-green-400">{formatCurrency(totalRevenue)}</p>
              </div>
              <div className="glass-card p-4 rounded-xl">
                  <p className="text-xs text-slate-400 uppercase font-bold">Transactions</p>
                  <p className="text-2xl font-black text-white">{sales.length}</p>
              </div>
          </div>
          
          {/* Expenses */}
          <div className="glass-panel p-5 rounded-2xl">
              <h3 className="font-bold text-white mb-3 flex items-center"><Wallet className="w-4 h-4 mr-2 text-orange-400"/> Expenses</h3>
              <form onSubmit={handleNewExpense} className="flex gap-2 mb-3">
                  <input type="text" placeholder="Desc" value={expDesc} onChange={e=>setExpDesc(e.target.value)} className="flex-1 bg-slate-900/50 border border-slate-700 rounded-lg p-2 text-xs text-white" />
                  <input type="number" placeholder="Amt" value={expAmount} onChange={e=>setExpAmount(e.target.value)} className="w-20 bg-slate-900/50 border border-slate-700 rounded-lg p-2 text-xs text-white" />
                  <button type="submit" className="bg-orange-500 text-white p-2 rounded-lg hover:bg-orange-600"><Plus className="w-4 h-4" /></button>
              </form>
              <div className="space-y-1">
                  {expenses.map(exp => (
                      <div key={exp.id} className="flex justify-between text-xs text-slate-400 bg-slate-900/30 p-2 rounded">
                          <span>{exp.description}</span>
                          <div className="flex gap-2">
                             <span className="text-red-400">-{exp.amount}</span>
                             <button onClick={() => onDeleteExpense(exp.id)} className="text-slate-600 hover:text-red-500"><Trash2 className="w-3 h-3"/></button>
                          </div>
                      </div>
                  ))}
              </div>
          </div>

          {/* Actions */}
          <div className="grid grid-cols-2 gap-4">
              <button 
                onClick={handleSaveAndArchive} 
                disabled={savingReport} 
                className="bg-slate-800 hover:bg-slate-700 text-white p-4 rounded-xl font-bold flex flex-col items-center justify-center gap-2 transition-all border border-white/5"
              >
                  {savingReport ? <Loader2 className="animate-spin" /> : <Save />}
                  Save Day
              </button>
              <button 
                onClick={() => {
                  if (confirmReset) {
                      onReset();
                      setConfirmReset(false);
                  } else {
                      setConfirmReset(true);
                      setTimeout(() => setConfirmReset(false), 3000);
                  }
                }}
                className={`p-4 rounded-xl font-bold flex flex-col items-center justify-center gap-2 transition-all border ${
                   confirmReset 
                   ? 'bg-red-600 text-white border-red-500' 
                   : 'bg-red-500/10 hover:bg-red-500/20 text-red-400 border-red-500/20'
                }`}
              >
                  {confirmReset ? <RefreshCw className="animate-spin"/> : <LogOut />}
                  {confirmReset ? 'Confirm Close?' : 'Close Shift'}
              </button>
          </div>
      </div>

    </div>
  );
};