import React, { useState, useMemo } from 'react';
import { InventoryItem, ProductType, FlowerGrade } from '../types';
import { Plus, Edit2, Save, X, ClipboardList, Minus, ShoppingCart, ArrowLeft, FileText, Loader2, ChevronUp, ChevronDown, ChevronRight, ArrowUpDown, Search, Trash2, CheckCircle2, RotateCcw, AlertTriangle, Download, Sparkles, Package, Flower2, Cigarette, Cookie, Flame } from 'lucide-react';
import { generateId } from '../utils/pricing';
import { translations, Language } from '../utils/translations';
import { jsPDF } from "jspdf";

interface InventoryManagerProps {
  inventory: InventoryItem[];
  onUpdateInventory: (item: InventoryItem) => void;
  onAdjustStock: (id: string, amount: number) => void;
  onDeleteInventory: (id: string) => void;
  onResetInventory: () => void;
  shopName: string;
  isSuperAdmin: boolean;
  language: Language;
  onBroadcastLowStock: (items: InventoryItem[]) => void;
}

export const InventoryManager: React.FC<InventoryManagerProps> = ({ inventory, onUpdateInventory, onAdjustStock, onDeleteInventory, onResetInventory, shopName, isSuperAdmin, language, onBroadcastLowStock }) => {
  const [isAdding, setIsAdding] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showOrderList, setShowOrderList] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [collapsedCategories, setCollapsedCategories] = useState<Set<string>>(new Set());
  const [isExporting, setIsExporting] = useState(false);
  
  // Sorting State
  const [sortConfig, setSortConfig] = useState<{ key: keyof InventoryItem; direction: 'asc' | 'desc' }>({ key: 'name', direction: 'asc' });
  
  // Custom Modal State
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [showResetConfirm, setShowResetConfirm] = useState(false);
  
  const t = translations[language];
  const activeItems = inventory.filter(item => item.stockLevel > 0);
  const outOfStockItems = inventory.filter(item => item.stockLevel <= 0);

  const [formState, setFormState] = useState<Partial<InventoryItem>>({
    category: ProductType.FLOWER,
    grade: FlowerGrade.MID,
    stockLevel: 0,
    price: 0
  });

  const getProductIcon = (type: ProductType) => {
    switch (type) {
      case ProductType.FLOWER: return <Flower2 className="w-4 h-4 text-green-500" />;
      case ProductType.PRE_ROLL: return <Cigarette className="w-4 h-4 text-gray-400" />;
      case ProductType.EDIBLE: return <Cookie className="w-4 h-4 text-orange-500" />;
      case ProductType.ACCESSORY: return <Flame className="w-4 h-4 text-red-500" />;
      case ProductType.OTHER: return <Package className="w-4 h-4 text-blue-500" />;
      default: return <Package className="w-4 h-4 text-slate-400" />;
    }
  };

  const handleSave = () => {
    if (!formState.name) return alert("Name is required");
    const item: InventoryItem = {
      id: editingId || generateId(),
      category: formState.category || ProductType.FLOWER,
      name: formState.name,
      grade: formState.category === ProductType.FLOWER ? formState.grade : undefined,
      stockLevel: Number(formState.stockLevel) || 0,
      price: Number(formState.price) || 0,
      lastUpdated: Date.now()
    };
    onUpdateInventory(item);
    resetForm();
  };

  const handleSort = (key: keyof InventoryItem) => {
    setSortConfig(current => ({
      key,
      direction: current.key === key && current.direction === 'asc' ? 'desc' : 'asc'
    }));
  };

  const handleExportPDF = () => {
    setIsExporting(true);
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const dateStr = new Date().toLocaleDateString();
    const timeStr = new Date().toLocaleTimeString();
    
    // -- HEADER --
    doc.setFontSize(22);
    doc.setTextColor(22, 163, 74); // Green 600
    doc.setFont("helvetica", "bold");
    doc.text(shopName, 15, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.setFont("helvetica", "normal");
    doc.text(`Inventory Report • ${dateStr} ${timeStr}`, pageWidth - 15, 20, { align: 'right' });
    doc.text(`Generated by System`, pageWidth - 15, 25, { align: 'right' });

    doc.setDrawColor(220);
    doc.setLineWidth(0.5);
    doc.line(15, 30, pageWidth - 15, 30);

    // -- SUMMARY CARDS --
    const totalItems = inventory.length;
    const lowStockCount = inventory.filter(i => i.stockLevel < 10 && i.stockLevel > 0).length;
    const outOfStockCount = inventory.filter(i => i.stockLevel <= 0).length;
    // Estimate value (price * stock) - using average price if missing
    const totalValue = inventory.reduce((sum, item) => sum + ((item.price || 0) * item.stockLevel), 0);

    // Box 1: Total Items
    doc.setFillColor(248, 250, 252); // Slate 50
    doc.roundedRect(15, 35, 45, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text("TOTAL SKUS", 20, 42);
    doc.setFontSize(16);
    doc.setTextColor(30);
    doc.setFont("helvetica", "bold");
    doc.text(totalItems.toString(), 20, 52);

    // Box 2: Low Stock
    doc.setFillColor(254, 242, 242); // Red 50
    doc.roundedRect(65, 35, 45, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(185, 28, 28); // Red 700
    doc.setFont("helvetica", "normal");
    doc.text("ALERTS / LOW", 70, 42);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`${lowStockCount + outOfStockCount}`, 70, 52);

    // Box 3: Est Value
    doc.setFillColor(240, 253, 244); // Green 50
    doc.roundedRect(115, 35, 65, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(21, 128, 61); // Green 700
    doc.setFont("helvetica", "normal");
    doc.text("EST. STOCK VALUE", 120, 42);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`${totalValue.toLocaleString()} THB`, 120, 52);

    let yPos = 70;

    // -- TABLE HEADER --
    const headers = ["#", "PRODUCT NAME", "CATEGORY", "DETAILS", "STOCK", "PRICE"];
    const colWidths = [10, 60, 30, 40, 20, 20]; // Total roughly 180 + margins
    const startX = 15;
    
    // Header Row Background
    doc.setFillColor(22, 163, 74); // Green 600
    doc.rect(startX, yPos, pageWidth - 30, 8, 'F');
    
    doc.setFontSize(8);
    doc.setTextColor(255);
    doc.setFont("helvetica", "bold");
    
    let currentX = startX + 2;
    headers.forEach((header, i) => {
        const align = i >= 4 ? 'right' : 'left';
        doc.text(header, currentX, yPos + 5.5);
        currentX += colWidths[i];
    });

    yPos += 8;

    // -- TABLE ROWS --
    doc.setTextColor(0);
    doc.setFont("helvetica", "normal");

    // Sort for PDF: Out of stock first, then by Category, then Name
    const sortedInventory = [...inventory].sort((a, b) => {
        if (a.stockLevel <= 0 && b.stockLevel > 0) return -1;
        if (a.stockLevel > 0 && b.stockLevel <= 0) return 1;
        return a.category.localeCompare(b.category) || a.name.localeCompare(b.name);
    });

    sortedInventory.forEach((item, index) => {
        if (yPos > 275) {
            doc.addPage();
            yPos = 20;
             // Header Row on new page
            doc.setFillColor(22, 163, 74);
            doc.rect(startX, yPos, pageWidth - 30, 8, 'F');
            doc.setTextColor(255);
            doc.setFont("helvetica", "bold");
            let cX = startX + 2;
            headers.forEach((header, i) => {
                doc.text(header, cX, yPos + 5.5);
                cX += colWidths[i];
            });
            yPos += 8;
            doc.setTextColor(0);
            doc.setFont("helvetica", "normal");
        }

        // Zebra Striping
        if (index % 2 === 1) {
            doc.setFillColor(248, 250, 252);
            doc.rect(startX, yPos, pageWidth - 30, 7, 'F');
        }

        currentX = startX + 2;
        
        // 1. Index
        doc.text((index + 1).toString(), currentX, yPos + 5);
        currentX += colWidths[0];

        // 2. Name
        const name = item.name.length > 25 ? item.name.substring(0, 25) + '...' : item.name;
        doc.text(name, currentX, yPos + 5);
        currentX += colWidths[1];

        // 3. Category
        doc.text(item.category, currentX, yPos + 5);
        currentX += colWidths[2];

        // 4. Details (Grade)
        const details = item.grade ? item.grade : '-';
        doc.text(details, currentX, yPos + 5);
        currentX += colWidths[3];

        // 5. Stock (Color coded)
        if (item.stockLevel <= 0) {
            doc.setTextColor(220, 38, 38); // Red
            doc.setFont("helvetica", "bold");
            doc.text("OUT", currentX, yPos + 5);
        } else if (item.stockLevel < 10) {
            doc.setTextColor(217, 119, 6); // Amber
            doc.text(item.stockLevel.toString(), currentX, yPos + 5);
        } else {
            doc.setTextColor(0);
            doc.text(item.stockLevel.toString(), currentX, yPos + 5);
        }
        doc.setFont("helvetica", "normal");
        doc.setTextColor(0);
        currentX += colWidths[4];

        // 6. Price
        const price = item.price ? item.price.toLocaleString() : '-';
        doc.text(price, currentX, yPos + 5);

        yPos += 7;
    });

    // Footer
    const pageCount = doc.internal.pages.length - 1;
    doc.setFontSize(8);
    doc.setTextColor(150);
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 290, { align: 'right' });
        doc.text(`The Green Spot POS System`, 20, 290);
    }

    doc.save(`${shopName.replace(/\s+/g, '_')}_Inventory_${new Date().toISOString().split('T')[0]}.pdf`);
    setIsExporting(false);
  };

  const toggleCategory = (category: string) => {
    const newCollapsed = new Set(collapsedCategories);
    if (newCollapsed.has(category)) newCollapsed.delete(category);
    else newCollapsed.add(category);
    setCollapsedCategories(newCollapsed);
  };

  const groupedInventory = useMemo<Record<string, InventoryItem[]>>(() => {
    const baseList = showOrderList ? outOfStockItems : activeItems;
    const filteredList = baseList.filter(item => item.name.toLowerCase().includes(searchQuery.toLowerCase()));
    
    const groups: Record<string, InventoryItem[]> = {};
    filteredList.forEach(item => {
        if (!groups[item.category]) groups[item.category] = [];
        groups[item.category].push(item);
    });
    return groups;
  }, [showOrderList, activeItems, outOfStockItems, searchQuery]);

  const resetForm = () => {
    setIsAdding(false);
    setEditingId(null);
    setFormState({ category: ProductType.FLOWER, grade: FlowerGrade.MID, stockLevel: 0, price: 0 });
  };

  const startEdit = (item: InventoryItem) => {
    setFormState(item);
    setEditingId(item.id);
    setIsAdding(true);
  };
  
  const confirmDelete = () => {
    if (deleteId) {
        onDeleteInventory(deleteId);
        setDeleteId(null);
    }
  }

  const confirmReset = () => {
      onResetInventory();
      setShowResetConfirm(false);
  }

  const availableCategories = Object.values(ProductType).filter(t => t !== ProductType.OTHER);

  return (
    <div className="glass-panel rounded-2xl overflow-hidden animate-fade-in flex flex-col h-full max-h-[85vh] relative">
      
      {/* Custom Confirmation Modal Overlay */}
      {(deleteId || showResetConfirm) && (
        <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
            <div className="bg-slate-900 border border-white/10 p-6 rounded-2xl shadow-2xl max-w-sm w-full transform transition-all scale-100">
                <div className="flex items-center justify-center w-12 h-12 bg-red-500/20 rounded-full mx-auto mb-4">
                   <AlertTriangle className="w-6 h-6 text-red-500" />
                </div>
                <h3 className="text-xl font-bold text-white mb-2 text-center">
                    {showResetConfirm ? 'Reset Entire Inventory?' : 'Delete Item?'}
                </h3>
                <p className="text-slate-400 mb-6 text-center text-sm">
                    {showResetConfirm 
                      ? "This will permanently delete ALL inventory items. This action cannot be undone." 
                      : "Are you sure you want to delete this item permanently?"}
                </p>
                <div className="flex gap-3">
                    <button 
                      onClick={() => { setDeleteId(null); setShowResetConfirm(false); }}
                      className="flex-1 py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold transition-colors"
                    >
                      Cancel
                    </button>
                    <button 
                      onClick={showResetConfirm ? confirmReset : confirmDelete}
                      className="flex-1 py-3 rounded-xl bg-red-600 hover:bg-red-500 text-white font-bold transition-colors shadow-lg shadow-red-900/20"
                    >
                      Confirm
                    </button>
                </div>
            </div>
        </div>
      )}

      <div className="p-4 border-b border-white/5 flex flex-col xl:flex-row justify-between items-start xl:items-center bg-slate-900/40 gap-3">
        
        <div className="flex items-center gap-3">
            <h2 className="text-lg font-bold text-white flex items-center">
                {showOrderList ? (
                    <>
                        <ShoppingCart className="w-5 h-5 mr-2 text-amber-500" />
                        {t.orderList} <span className="ml-2 px-2 py-0.5 bg-amber-500/20 text-amber-400 text-xs rounded-full">{outOfStockItems.length}</span>
                    </>
                ) : (
                    <>
                        <Package className="w-5 h-5 mr-2 text-indigo-500" />
                        {t.inventoryManagement}
                    </>
                )}
            </h2>
        </div>

        <div className="flex items-center gap-2 w-full xl:w-auto">
            <div className="relative flex-1">
                <Search className="absolute left-3 top-2 h-4 w-4 text-slate-500" />
                <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder={t.searchPlaceholder}
                    className="w-full pl-9 pr-4 py-1.5 text-sm bg-slate-950/50 border border-slate-700 rounded-lg text-white focus:border-green-500 outline-none"
                />
            </div>

            <button 
              onClick={() => setShowOrderList(!showOrderList)}
              className={`p-2 rounded-lg transition-colors ${showOrderList ? 'bg-slate-700 text-white' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
              title={showOrderList ? "Show All Items" : "Show Order List"}
            >
              {showOrderList ? <ArrowLeft className="w-4 h-4" /> : <ClipboardList className="w-4 h-4" />}
            </button>
            
            <button 
              onClick={handleExportPDF}
              disabled={isExporting}
              className={`p-2 rounded-lg bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700 transition-colors ${isExporting ? 'opacity-50 cursor-not-allowed' : ''}`}
              title="Export Inventory PDF"
            >
              {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <div className="flex items-center"><Download className="w-4 h-4" /></div>}
            </button>
            
            {!showOrderList && isSuperAdmin && (
                <>
                    <button 
                      onClick={() => setIsAdding(true)}
                      className="bg-green-600 hover:bg-green-500 text-white p-2 rounded-lg transition-colors shadow-lg shadow-green-900/20"
                    >
                      <Plus className="w-4 h-4" />
                    </button>
                    <button 
                        onClick={() => setShowResetConfirm(true)}
                        className="bg-red-500/10 hover:bg-red-500/20 text-red-400 p-2 rounded-lg border border-red-500/20 transition-colors"
                        title="Reset Inventory"
                    >
                        <RotateCcw className="w-4 h-4" />
                    </button>
                </>
            )}
        </div>
      </div>

      {isAdding && (
         <div className="bg-slate-800/80 p-4 border-b border-white/5 backdrop-blur-sm animate-fade-in">
             <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
                 <input type="text" placeholder="Name" value={formState.name||''} onChange={e=>setFormState({...formState, name: e.target.value})} className="bg-slate-900 border border-slate-700 rounded-lg p-2 text-sm text-white" />
                 <select value={formState.category} onChange={e=>setFormState({...formState, category: e.target.value as ProductType})} className="bg-slate-900 border border-slate-700 rounded-lg p-2 text-sm text-white">
                     {availableCategories.map(c=><option key={c} value={c}>{c}</option>)}
                 </select>
                 {formState.category === ProductType.FLOWER ? (
                     <select value={formState.grade} onChange={e=>setFormState({...formState, grade: e.target.value as FlowerGrade})} className="bg-slate-900 border border-slate-700 rounded-lg p-2 text-sm text-white">
                         {Object.values(FlowerGrade).map(g=><option key={g} value={g}>{g}</option>)}
                     </select>
                 ) : (
                     <input type="number" placeholder="Price" value={formState.price||''} onChange={e=>setFormState({...formState, price: parseFloat(e.target.value)})} className="bg-slate-900 border border-slate-700 rounded-lg p-2 text-sm text-white" />
                 )}
                 <input type="number" placeholder="Stock" value={formState.stockLevel} onChange={e=>setFormState({...formState, stockLevel: parseFloat(e.target.value)})} className="bg-slate-900 border border-slate-700 rounded-lg p-2 text-sm text-white" />
             </div>
             <div className="flex justify-end gap-2">
                 <button onClick={resetForm} className="text-slate-400 text-xs hover:text-white px-3 py-2">Cancel</button>
                 <button onClick={handleSave} className="bg-green-600 text-white text-xs font-bold px-4 py-2 rounded-lg hover:bg-green-500">Save Product</button>
             </div>
         </div>
      )}

      <div className="flex-1 overflow-auto custom-scrollbar p-2">
        <table className="w-full text-sm text-left border-collapse min-w-[500px]">
          <thead className="text-xs text-slate-500 uppercase bg-slate-900/40 sticky top-0 z-10 backdrop-blur-sm">
             <tr>
               <th className="px-4 py-3 font-bold cursor-pointer hover:text-white transition-colors" onClick={() => handleSort('name')}>
                   <div className="flex items-center">
                       {t.productName}
                       {sortConfig.key === 'name' && (
                           <ArrowUpDown className={`w-3 h-3 ml-1 ${sortConfig.direction === 'asc' ? 'text-green-500' : 'text-red-500'}`} />
                       )}
                   </div>
               </th>
               <th className="px-4 py-3 font-bold text-right">{t.grade} / Price</th>
               <th className="px-4 py-3 font-bold text-right cursor-pointer hover:text-white transition-colors" onClick={() => handleSort('stockLevel')}>
                   <div className="flex items-center justify-end">
                       {t.stock}
                       {sortConfig.key === 'stockLevel' && (
                           <ArrowUpDown className={`w-3 h-3 ml-1 ${sortConfig.direction === 'asc' ? 'text-green-500' : 'text-red-500'}`} />
                       )}
                   </div>
               </th>
               {isSuperAdmin && <th className="px-4 py-3 font-bold text-right">Actions</th>}
             </tr>
          </thead>
          <tbody className="divide-y divide-white/5">
            {Object.keys(groupedInventory).length === 0 ? (
               <tr><td colSpan={4} className="text-center py-12 text-slate-500">No items found.</td></tr>
            ) : (
              Object.entries(groupedInventory).sort((a, b) => a[0].localeCompare(b[0])).map(([category, items]) => {
                const isCollapsed = collapsedCategories.has(category);
                
                // Sorting logic for items within category
                const sortedItems = [...(items as InventoryItem[])].sort((a, b) => {
                    const { key, direction } = sortConfig;
                    let valA: any = a[key as keyof InventoryItem];
                    let valB: any = b[key as keyof InventoryItem];
                    
                    if (key === 'name') {
                        valA = (a.name || '').toLowerCase();
                        valB = (b.name || '').toLowerCase();
                    }
                    
                    if (valA < valB) return direction === 'asc' ? -1 : 1;
                    if (valA > valB) return direction === 'asc' ? 1 : -1;
                    return 0;
                });

                return (
                  <React.Fragment key={category}>
                    <tr onClick={() => toggleCategory(category)} className="bg-slate-900/30 cursor-pointer hover:bg-slate-900/50">
                      <td colSpan={isSuperAdmin ? 4 : 3} className="px-4 py-2">
                        <div className="flex items-center justify-between">
                            <span className="font-bold text-slate-300 text-xs uppercase tracking-widest">{category}</span>
                            {isCollapsed ? <ChevronRight className="w-4 h-4 text-slate-600" /> : <ChevronDown className="w-4 h-4 text-slate-600" />}
                        </div>
                      </td>
                    </tr>
                    
                    {!isCollapsed && sortedItems.map((item) => (
                      <tr key={item.id} className="hover:bg-white/5 transition-colors group">
                        <td className="px-4 py-3 font-medium text-slate-200">
                          <div className="flex items-center gap-2">
                            {getProductIcon(item.category)}
                            {item.name}
                          </div>
                        </td>
                        <td className="px-4 py-3 text-right">
                          {item.grade ? (
                            <span className="bg-slate-800 text-slate-400 px-2 py-0.5 rounded text-[10px] uppercase font-bold border border-slate-700">{item.grade}</span>
                          ) : item.price ? (
                              <span className="font-mono text-xs text-slate-400">{item.price} ฿</span>
                          ) : null}
                        </td>
                        <td className="px-4 py-3 text-right">
                           <div className="flex items-center justify-end gap-2">
                               <span className={`font-mono text-sm font-bold ${item.stockLevel < 10 ? 'text-amber-500' : 'text-slate-300'}`}>{item.stockLevel}</span>
                               <div className="flex flex-col opacity-0 group-hover:opacity-100 transition-opacity">
                                   <button onClick={() => onAdjustStock(item.id, 1)} className="text-[10px] text-green-500 hover:text-green-400"><ChevronUp className="w-3 h-3"/></button>
                                   <button onClick={() => onAdjustStock(item.id, -1)} className="text-[10px] text-red-500 hover:text-red-400"><ChevronDown className="w-3 h-3"/></button>
                               </div>
                           </div>
                        </td>
                        {isSuperAdmin && (
                            <td className="px-2 py-3 text-right">
                                <div className="flex items-center justify-end gap-1">
                                    <button onClick={() => startEdit(item)} className="p-1.5 text-slate-500 hover:text-white"><Edit2 className="w-3 h-3" /></button>
                                    <button 
                                      onClick={(e) => {
                                        e.stopPropagation(); // Stop row clicks
                                        setDeleteId(item.id);
                                      }} 
                                      className="p-1.5 text-slate-600 hover:text-red-400"
                                    >
                                      <Trash2 className="w-3 h-3" />
                                    </button>
                                </div>
                            </td>
                        )}
                      </tr>
                    ))}
                  </React.Fragment>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
